### PR TITLE
PostgreSQL support

### PR DESCRIPTION
**Pull request by georgweiss**
The pull request contains one single commit which implements support for PostgreSQL. 

The file README.postgresql contains further information.

### CODE REVIEW

**Comment by mdavidsaver** [comment]
@georgweiss Can you re-target this PR against master in https://github.com/mdavidsaver/masarService so that the diff doesn't include all of the changes in that branch as well?

**Comment by georgweiss** [comment]
Not sure I understand the difference in changing the target. The end result should be the same, right?

**Comment by mdavidsaver** [comment]
Right now the diff includes my changes as well as yours.  I'd like to see
only your changes.

**Comment by georgweiss** [comment]
I see. Guess I have to ditch this PR and create a new one?

**Pull request closed without merging**
