### PR TITLE
minimasar server

### PR DESCRIPTION
**Pull request by mdavidsaver**
A new server (and db schema).

TODO items:

* Switch from bundled P4P to external dependency
* DB migration script?

### CODE REVIEW

**Comment by mdavidsaver** [comment]
I've made a first release of P4P.

On this branch, there is a conversion script to copy from an existing sqlite .db file to a new one with the new minimasar schema.  I made a quick attempt to update the pyqt client to use P4P, though more work will probably be needed.  With this change, all of the c++ code in this repo has been dropped!  What remains is < 6K lines of python.

**Comment by mdavidsaver** [comment]
There are a few unit tests under python/minimasar/test/ though I haven't yet configured travis-ci to build/run them.

**Comment by mdavidsaver** [comment]
To make a long story short.  I think this work is finally ready for release.

**Comment by shengb** [comment]
Did not see serious issue there.

One minor in db.py:
      from types import NoneType
NoneType has been removed in Python3. It would be better to use type(None) instead if importing.

Some clean up, which do not matter.
There are some unnecessary import which are not used, for example:
in gather.ca:
from functools import partial

in convert: (json is not used)
import pickle, json

**Comment by mdavidsaver** [comment]
Should now work with py3 https://travis-ci.org/mdavidsaver/masarService

**Pull request merged**
